language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly
  
matrix:
  allow_failures:
    - rust: nightly
    
script:
  - |
      cargo build &&
      cargo test &&
      cargo bench
      
notifications:
  email:
    - sgrangan01@gmail.com
    
branches:
  only: master
